spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: MySQL04
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql

